name: seyi_kyc_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  flutter_svg:
  get:
  selectable_container: ^0.1.4
  intl: ^0.16.1
  dotted_border: ^1.0.6
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2

  flutter_otp: ^0.3.2

  wc_form_validators: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
